name: Tooling CI/CD
on: [push, pull_request]

jobs:
  cli-build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Build CLI
        run: npm run build:cli
      - name: Test CLI commands
        run: npm run test:cli
      - name: Test project scaffolding
        run: npm run test:scaffolding
      - name: Lint code
        run: npm run lint
  
  build-tools:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Build tools
        run: npm run build:tools
      - name: Test build configurations
        run: npm run test:build-configs
      - name: Test deployment tools
        run: npm run test:deployment
  
  environment-validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Test environment validation
        run: npm run test:environment
      - name: Validate package dependencies
        run: npm run validate:dependencies
